# (Hz) n times per second.
FPS = 60

# (N/s) 845kN per Engine, 1 Engine Fired - assumed 100kN for side engine thrusters
MAIN_ENGINE_POWER = 845000
SIDE_ENGINE_POWER = 100000
ORIENTATION_ENGINE_POWER = 60

# (px)
VIEWPORT_W = 1300
VIEWPORT_H = 800

# (m)
WORLD_SCALAR = 0.5
WORLD_W = VIEWPORT_W * WORLD_SCALAR
WORLD_H = VIEWPORT_H * WORLD_SCALAR

# (m)
SEA_LEVEL = 50

# (m)
GOAL_H = 5
GOAL_W = 100
GOAL_X_SCALED = 0.5

GOAL_MIN_X = 0.2
GOAL_MAX_X = 0.8


# (m) 3x40
LANDER_DIAMETER = 3 
LANDER_HEIGHT   = 40
LANDER_POLY = [
    (-LANDER_DIAMETER/2, +LANDER_HEIGHT), (-LANDER_DIAMETER/2, 0), 
    (+LANDER_DIAMETER/2, +LANDER_HEIGHT), (+LANDER_DIAMETER/2, 0),
]

# (kg/m^3)
LANDER_DENSITY = 200.0 # equates to 24,000kg dry mass weight
SEA_LEVEL_DENSITY    = 1.225

# (m) 
SIDE_ENGINE_HEIGHT = 40
SIDE_ENGINE_AWAY = 3

# (m)
LEG_AWAY = 4
LEG_DOWN = 2
LEG_W, LEG_H = 0.5, 4
LEG_SPRING_TORQUE = 10

# (m/s)
START_VELOCITY = (0,-80)

# Sensor failure probabilies
ACCELEROMETER_FAILURE_CHANCE = 0.9
GPS_FAILURE_CHANCE = 0.5
ROLL_FAILURE_CHANCE = 0.5
SIDE_BOOSTER_FAILURE_CHANCE = 0.5

